# Getting Started

## Requesting an Account

RRN is available to all Rotman researchers. To request an account, please email TD Management Data and Analytics Lab at tdmdal@rotman.utoronto.ca. Once your account is created, you will receive an activation email together with login instructions. The process usually takes less than 1 business day.


## Logging on to RRN

You will need an SSH (Secure Shell) client to log on to RRN. For Windows users, we recommend [MobaXterm](https://mobaxterm.mobatek.net/). Mac users can use the SSH client provided by the pre-installed [Terminal](https://support.apple.com/en-ca/guide/terminal/welcome/mac) App. In addition, in order to run applications on the server with graphic user interfaces (GUI), Mac users should also install [XQuartz](https://www.xquartz.org/).

To log on to RRN,

1) Open a terminal window. Windows users first launch the MobaXterm app, and then click the "Start local terminal" button in the home tab. Mac users simply run the Terminal app.

2) Type the following command. (Replace `yourUserName` with your user name.)

```{bash eval=FALSE}
ssh -X yourUserName@rrlogin.cac.queensu.ca
```

The `-X` option enables graphics forwarding so you can run applications with GUI.


## Resetting Password

If you forget your password, you can go to [this page](https://login.cac.queensu.ca/pwr) to reset your password.


## Directory Structure and Disk Quota

You have three folders to store your data. All of them can only be accessed by you.

Folder          | Path                                            | Quota       | Usage
:---------------|:------------------------------------------------|:------------|:-------------------
home folder     | `/global/home/yourUserName/`                    | 3T          | main storage
project folder  | `/global/project/rotman_research/yourUserName/` | 50T shared  | additional storage
scratch folder  | `/global/scratch/yourUserName/`                 | 5T          | temporary storage

Note that your project folder shares 50T disk space with other Rotman project folders.

The home folder is the landing folder when you log on to the system. The project and scratch folders can also be accessed via two symbolic links in your home folder: `rotman_research` and `scratch`. (The symbolic links are like shortcuts in Windows.)

You can use the `myquota` command to see your disk quota and current usage.

In addition to the above folders, if you need another project folder for collaboration (i.e. share with other researchers), email us and we can help you set it up.


## Transferring Files

It's most convenient to use an SFTP (Secure File Transfer Protocol) client to transfer files between your local computer and RRN. [WinSCP](https://winscp.net/eng/download.php) is a great free SFTP client for Windows users. Mac users can install [FileZilla](https://filezilla-project.org/download.php?show_all=1). Use the following information to configure your SFTP client.

* File protocol: SFTP
* Host name: `rrlogin.cac.queensu.ca`
* User name: (your username)
* Password: (your password)
* Port: 22

If you prefer to use command line tools, `scp` and `rsync` are good options.


## Loading Software

RRN uses [Environment Modules](https://lmod.readthedocs.io/en/latest/) to manage its software. Environment modules treat each software and its associated files as a distinct package to be loaded on demand. It resolves conflicts between multiple versions of a software package and configures the environment necessary for running a package.

Below are a few commonly used module command.

Description                                 | Module Command
:-------------------------------------------| :--------------------------------- 
List all available software packages        | `module avail`        
Display a short description of a package    | `module spider packageName`
Load a package                              | `module load packageName`
Load a specific version of a package        | `module load packageName/version`
List currently loaded packages              | `module list`
Unload a package                            | `module unload packageName`
Unload all packages                         | `module purge`

For example, to load the Anaconda Python 3 package, type the below command.

```{bash eval=FALSE}
module load anaconda/3.5.3
```

RRN has a large collection of software tools installed. Section [Using Software] provides more details on how to setup some commonly used ones.
