# Using Software

## Best Practice

### Interactive mode vs batch mode

Most applications can run either in interactive mode or in batch mode. For small jobs, it really doesn't matter which one you choose. For medium to large jobs, you could still code and debug your work in the interactive mode, but you should run your work in batch mode once it's fully tested as probably you don't want to wait in front of the screen for your job to finish. If you use batch mode, you'll have the convenience of logging off the system and logging in later to check the result. You can do so by pre- and post-face your application's batch mode command with the Linux command `nohup` and control operator `&`.

```{bash eval=FALSE}
nohup <batch mode command> &
```

`nohup` prevents your job from being killed when you log off the system. The `&` at the end makes the command run in the background. For example, suppose you use Stata and you have a do file named `filename.do` that takes hours to run, you could run it in batch mode as below.

```{bash eval=FALSE}
nohup stata -b do filename &
```

### RRN vs compute node

RRN is actually integrated with a High-Performance Computing (HPC) system. The HPC system has a cluster of around 100 compute nodes and hundreds of CPUs. Since RRN is shared by many Rotman researchers, if you have a super compute-intensive job, you should consider submitting it to the compute nodes instead of running it on RRN. See [this CAC document](https://cac.queensu.ca/wiki/index.php/SLURM) to learn how to submit jobs to compute nodes.


## Using Python

### Setup

Different versions and distributions of Python are available on RRN including Standard Python 2 and 3 releases, Anaconda Distribution 2 and 3, and Python 2 and 3 with MPI4Py and Scipy stack. (Use `module avail` to list all available software on RRN.)

We recommend you use Anaconda Distribution 3 as it comes with a collection of useful Python packages and a good package and environment manager `conda`. Load the Anaconda Python 3 as below.

```{bash eval=FALSE}
module load anaconda/3.5.3
```

See more on setting up virtual environment for Python projects below (section [Installing packages]).

### Interactive mode (Python console)

To use Python in interactive mode (Python console), type `python` in the terminal.

### Batch mode

To use Python in batch mode, use

```{bash eval=FALSE}
python mycode.py
```

To capture standard output `stdout` and standard error `stderr` (usually displayed on screen) in a log file, use

```{bash eval=FALSE}
python mycode.py &> mycode_log.txt
```

`&>` redirects standard output and error streams to a file specified. Nothing will be printed in the terminal. If the file already exists, it gets overwritten.

Pre- and post-face the above command with the Linux command `nohup` and control operator `&` so that the job will run in background and won't be killed even you log off the system (see section [Interactive mode vs batch mode]).

```{bash eval=FALSE}
nohup python mycode.py &> mycode_log.txt &
```

### Installing packages

The best practice to manage Python packages is to create a virtual environment for each of your Python project. In a project virtual environment, you only need to install the packages required for that specific project. In that way, you can avoid potential package conflicts between projects.

We assume you use Anaconda Python 3 distribution on RRN. Below are steps to setup a virtual environment and install new packages.

1. Load Anaconda Python 3 distribution.

```{bash eval=FALSE}
module load anaconda/3.5.3
```

2. Create a virtual environment
.
```{bash eval=FALSE}
conda create --name myenv
```

`conda` is the package management system. `myenv` is the specified environment name. (You may want to pick your own name.)

3. Activate the virtual environment.

```{bash eval=FALSE}
source activate myenv
```

Note: For conda 4.6 or later version, you can use `conda activate myenv` to activate the environment. The default conda version on RNN is 4.5.11 (use `conda --version` to see it). However, if you still want to use `conda activate myenv` (for future proof), do the following.

Run the below command once, logout, and re-login. Once you login, run (1) again to load the anaconda module. This command adds a line to `.bashrc` file so that you can use `conda activate` to activate the virtual environment you just created in step (2)

```{bash eval=FALSE}
echo ". /global/software/python/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc
```

4. Install packages.

Now you are inside your virtual environment. You should see `(myenv)` in the terminal prompt. This is an isolated environment that you can manage the packages to be installed. For example, you can install `tensorflow` and `keras` by using `conda install <packageName>`. All package dependencies will be installed automatically. 

```{bash eval=FALSE}
conda install tensorflow
conda install keras
```

Note that a new virtual environment has no packages pre-installed (except Python standard libraries).

If you are not able to install a package with `conda install <pacakgeName>` (packages built and maintained by Anaconda official channel) or `conda install -c conda-forge <packageName>` (packages built and maintained by conda community),  you can still try `pip install <pacakgeName>`, although you would need to first install `pip` using `conda install pip`.

5. Return to base environment.

After you're done with Python, type `source deactivate` to return to the base environment. (If you have followed the "Note" in step 3, you can use `conda deactivate` instead.)

Next time, all you need to do is step (1) and (3) to start the virtual environment and using Python.

See more on `conda` at its [official document page](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-envs).

### Run Python on compute nodes

For large compute-intensive Python jobs, consider submitting them to the compute nodes (see [RRN vs compute node]). The following document on the [CAC Wiki](https://cac.queensu.ca/wiki/index.php/Main_Page) site can get you started.

* [How to run jobs using a scheduler](https://cac.queensu.ca/wiki/index.php/SLURM)


## Using R

todo


## Using Matlab

### Setup

Send a signed [MATLAB usage statement form](https://cac.queensu.ca/wp-content/uploads/2017/05/cac-matlab-statement-new.pdf) to cac.admin@queensu.ca and cc tdmdal@rotman.utoronto.ca. This will add you to the matlab group that allows access to the software. To check if you have been authorized access, type `groups` while logged on to the system. If `matlab` appears in the output, you are good to go!

Type `module avail matlab` to see available Matlab versions, and then load the one you want to use. Currently, two versions of Matlab are installed (R2017a and R2018b). For example, if you want to use Matlab 2018b, type

```{bash eval=FALSE}
module load matlab/R2018b
```

### Interactive mode without GUI

To start Matlab in interactive mode without GUI, type the command below.

```{bash eval=FALSE}
matlab -nodisplay -nojvm -nosplash
```

### Interactive mode with GUI

To start Matlab in interactive mode with GUI, simply type `matlab` in the terminal.

If you use Matlab/R2017a, you may find the Matlab GUI a bit lagging. In this case, in the folder where you start Matlab, create a file named `java.opts` and add the following line in it. This should resolve the GUI problem.

```
-Dsun.java2d.pmoffscreen=false

```

### Batch mode

To run Matlab in batch mode, use

```{bash eval=FALSE}
matlab -nodisplay -nodesktop -nojvm -nosplash <mycode.m >output.txt
```

The `<` symbol tells the `matlab` command to take the Matlab m file `mycode.m` as input. The `>` symbol redirects the output to the `output.txt` file instead of printing it to the screen.

Pre- and post-face the above command with the Linux command `nohup` and control operator `&` so that the job will run in background and won't be killed even you log off the system (see section [Interactive mode vs batch mode]).

```{bash eval=FALSE}
nohup matlab -nodisplay -nodesktop -nojvm -nosplash <mycode.m >output.txt &
```


### Run Matlab on compute nodes

For large compute-intensive Matlab jobs, consider submitting them to the compute nodes (see [RRN vs compute node]). The following two documents on the [CAC Wiki](https://cac.queensu.ca/wiki/index.php/Main_Page) site can get you started.

* [How to run jobs using a scheduler](https://cac.queensu.ca/wiki/index.php/SLURM)
* [An example of a MATLAB job script](https://cac.queensu.ca/wiki/index.php/Software:matlab)


## Using Stata

### Setup

The environment module hasn't been configured for Stata yet so you would need to manually set the path to use Stata. Type the command below in the terminal.

```{bash eval=FALSE}
export PATH=$PATH:/global/software/stata15
```

### Interactive mode without GUI

To start Stata/IC in interactive mode without GUI (Stata console mode), type `stata` in the terminal.

Use `stata-se` for Stata/SE and `stata-mp` for Stata/MP.

### Interactive mode with GUI

To start Stata/IC in interactive mode with GUI, use `xstata` (use `xstata-se` for Stata/SE and `xstata-mp` for Stata/MP). You will lose your terminal command line prompt once the Stata GUI is running.

Alternatively, use `xstata &` (`xstata-se &` or `xstata-mp &`) to run the command in background and return the command line prompt.

### Batch mode

To run Stata/IC in batch mode, use

```{bash eval=FALSE}
stata -b do filename &
```

Stata will execute the commands in `filename.do` and will automatically save the output in `filename.log`. The `&` at the end tells Linux to run the command in the background, freeing up your command line prompt.

If your code takes a long time to run, you may wish to start a batch Stata job, log off from your terminal, and log back in later to retrieve the output. To do this, preface the previous command with `nohup`.

```{bash eval=FALSE}
nohup stata -b do filename &
```

`nohup` prevents your job from being killed when you log off the system.

### A note on Stata/MP

We have Stata/MP 32-core installed on the system. Since RRN is a 32-core node shared by many users, we request that you set the number of processors for Stata/MP to be less than 16 when you use it on RRN.

Use `set processors #` to set the number of processors for Stata/MP. For example,

```{stata eval=FALSE}
set processors 12
```

Put it on the first line in your do file or run it first if you use interactive mode.

If you have a large workload that requires many cores and hours to run, your should consider submitting your job to the compute nodes on the HPC system. In that case, you can request a 32-core node to take full advantage of the 32-core Stata/MP licence. (See [How to run jobs using a scheduler](https://cac.queensu.ca/wiki/index.php/SLURM) on the [CAC Wiki](https://cac.queensu.ca/wiki/index.php/Main_Page) site to get started.)